# Generated by Django 5.1.6 on 2025-02-25 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_reporte",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y Hora del Reporte"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "foto_transportista",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="reportes/",
                        verbose_name="Foto Guía Transportista",
                    ),
                ),
                (
                    "foto_remitente",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="reportes/",
                        verbose_name="Foto Guía Remitente",
                    ),
                ),
                (
                    "guia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes",
                        to="myapp.guiaremision",
                        verbose_name="Guía de Remisión",
                    ),
                ),
            ],
        ),
    ]
